"""empty message

Revision ID: 74f546cd8704
Revises: 535ef66c13de
Create Date: 2022-08-11 16:38:20.041132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74f546cd8704'
down_revision = '535ef66c13de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'name')
    op.drop_column('Show', 'num_upcoming_shows')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('num_upcoming_shows', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('Show', sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
