"""empty message

Revision ID: c7dc01881cec
Revises: a224e75e1f03
Create Date: 2022-08-07 22:29:30.075513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7dc01881cec'
down_revision = 'a224e75e1f03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo_lists', sa.Column(
        'all_completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo_lists', 'all_completed')
    # ### end Alembic commands ###
