"""empty message

Revision ID: 5fccad5635b7
Revises: 
Create Date: 2022-08-03 19:38:32.894272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fccad5635b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('table2')
    op.drop_table('table1')
    op.add_column('people', sa.Column('gender', sa.Boolean(), nullable=True))
    op.execute('UPDATE people SET gender = False WHERE gender IS NULL;')
    op.alter_column('people', 'gender', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('people', 'gender')
    op.create_table('table1',
                    sa.Column('id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('description', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('id', name='table1_pkey')
                    )
    op.create_table('table2',
                    sa.Column('id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('completed', sa.BOOLEAN(), server_default=sa.text(
                        'false'), autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('id', name='table2_pkey')
                    )
    # ### end Alembic commands ###
